version: '3.8'

services:
  lifting-db:
    image: postgres:alpine
    container_name: lifting-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  lifting-app:
    build: .
    container_name: lifting-app
    environment:
      - DB_SERVER=lifting-db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
    ports:
      - 8080:8080
    links:
      - lifting-db
